In [2]:
import numpy
from matplotlib import pyplot as plt

def guak(size,size_y=None):
  size=int(size)
  if not size_y:
    size_y=size
  else:
    size_y=int(size_y)
  x,y=numpy.mgrid[-size:size+1, -size_y:size_y+1]
  g=numpy.exp(-(x**2/float(size)+y**2/float(size_y)))
  return g / g.sum()

guak_arr = guak(3)
print(guak_arr)
plt.imshow(guak_arr, cmap=plt.get_cmap('jet'), interpolation='nearest')
plt.colorbar()
plt.show()

[[0.00026475 0.00140172 0.00381028 0.00531767 0.00381028 0.00140172
  0.00026475]
 [0.00140172 0.00742141 0.02017349 0.02815437 0.02017349 0.00742141
  0.00140172]
 [0.00381028 0.02017349 0.05483722 0.07653151 0.05483722 0.02017349
  0.00381028]
 [0.00531767 0.02815437 0.07653151 0.10680833 0.07653151 0.02815437
  0.00531767]
 [0.00381028 0.02017349 0.05483722 0.07653151 0.05483722 0.02017349
  0.00381028]
 [0.00140172 0.00742141 0.02017349 0.02815437 0.02017349 0.00742141
  0.00140172]
 [0.00026475 0.00140172 0.00381028 0.00531767 0.00381028 0.00140172
  0.00026475]]


In [3]:
def guak(size,size_y=None):
  size=int(size)
  if not size_y:
    size_y=size
  else:
    size_y=int(size_y)
  x,y=numpy.mgrid[-size:size+1, -size_y:size_y+1]
  g=numpy.exp(-(x**2/float(size)+y**2/float(size_y)))
  return g / g.sum()

guak_arr = guak(1)
print(guak_arr)
plt.imshow(guak_arr, cmap=plt.get_cmap('jet'), interpolation='nearest')
plt.colorbar()
plt.show()

[[0.04491922 0.12210311 0.04491922]
 [0.12210311 0.33191066 0.12210311]
 [0.04491922 0.12210311 0.04491922]]


In [15]:
from skimage import io, img_as_float
from scipy import ndimage as nd
from matplotlib import pyplot as plt
import numpy as np

img = io.imread("/content/noisy.jpg")
gau = nd.gaussian_filter(img,sigma=3)
plt.imshow(gau)


In [5]:
plt.imshow(img)

In [12]:
med = nd.median_filter(img,size=4)
plt.imshow(med)

In [16]:
img1 = img_as_float(io.imread("/content/noisy.jpg"))

from skimage.restoration import denoise_nl_means, estimate_sigma
sig = np.mean(estimate_sigma(img1, multichannel=True))
nlm = denoise_nl_means(img1, h=1.15 * sig, fast_mode=True, patch_size=5, patch_distance=3, multichannel=True)
plt.imshow(nlm)

<ipython-input-16-13b46820a4c3>:4: FutureWarning: `multichannel` is a deprecated argument name for `estimate_sigma`. It will be removed in version 1.0. Please use `channel_axis` instead.
  sig = np.mean(estimate_sigma(img1, multichannel=True))
<ipython-input-16-13b46820a4c3>:5: FutureWarning: `multichannel` is a deprecated argument name for `denoise_nl_means`. It will be removed in version 1.0. Please use `channel_axis` instead.
  nlm = denoise_nl_means(img1, h=1.15 * sig, fast_mode=True, patch_size=5, patch_distance=3, multichannel=True)
